spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookLibrary

logging:
  level:
    ROOT: ERROR

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.homework.mongock.changelog