DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS author;
CREATE TABLE author(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE genre(id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL);
CREATE TABLE book(id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL,author VARCHAR(255),
                  genre VARCHAR(255));